// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpdeaonvufyillrclruc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZGVhb252dWZ5aWxscmNscnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDI3MDAsImV4cCI6MjA1OTc3ODcwMH0.gz96NFvG761zteznVSgJdvIWpYP-Z7e6bGar88PkQiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);